### ISSUE TITLE
Sv32 page table constructoin confusion

### ISSUE THREAD

**Issue by FahkingName** [itsubaidrehman/RISC-V_arch_test#1]
Thanks for your work, but I get confused while reading your code.
In task_5/test.S, you build the level 1 page table via level_1_pet:
https://github.com/itsubaidrehman/RISC-V_arch_test/blob/3d430a79a2add44ab954393dadd07cdaa091a414/task_5/test.S#L187-L200
Isn't the pte in level 1 page table supposed to be a pointer to the next level page table? But it seems that you calculate it by shifting the physical address 0x80000000 stored in a1.
https://github.com/itsubaidrehman/RISC-V_arch_test/blob/3d430a79a2add44ab954393dadd07cdaa091a414/task_5/test.S#L27 
Could you explain the purpose of this? Much appreciated!

**Comment by itsubaidrehman** [comment]
@FahkingName if the level1 pte is the pointer to the next level (level0) pte, ppn stored in that pte would be used to calculate the base address of the level0 pte thats why to setup the page table entry at level1, physical address is shifted to extract only the PPNs of Physical address to be stored at PTE.
Let me know if still want to know?

**Comment by FahkingName** [comment]
> @FahkingName if the level1 pte is the pointer to the next level (level0) pte, ppn stored in that pte would be used to calculate the base address of the level0 pte thats why to setup the page table entry at level1, physical address is shifted to extract only the PPNs of Physical address to be stored at PTE. Let me know if still want to know?

Thanks for your reply.
I'm still kinda confused that, since the level1 PTE stores the base address of next level (level0) page table, why do you shift the physical address 0x80000000, rather than the base address of level0 page table accessed with `la t2, inner_page_table`?

**Comment by FahkingName** [comment]
> @FahkingName if the level1 pte is the pointer to the next level (level0) pte, ppn stored in that pte would be used to calculate the base address of the level0 pte thats why to setup the page table entry at level1, physical address is shifted to extract only the PPNs of Physical address to be stored at PTE. Let me know if still want to know?

Thanks for your reply.
I'm still kinda confused that, since the level1 PTE stores the base address of next level (level0) page table, why do you shift the physical address 0x80000000, rather than the base address of level0 page table accessed with `la t2, inner_page_table`?

**Comment by FahkingName** [comment]
> @FahkingName if the level1 pte is the pointer to the next level (level0) pte, ppn stored in that pte would be used to calculate the base address of the level0 pte thats why to setup the page table entry at level1, physical address is shifted to extract only the PPNs of Physical address to be stored at PTE. Let me know if still want to know?

Thanks for your reply.
I'm still kinda confused that, since the level1 PTE stores the base address of next level (level0) page table, why do you shift the physical address 0x80000000, rather than the base address of level0 page table accessed with, let's say, `la t2, inner_page_table`?

**Comment by itsubaidrehman** [comment]
I have shifted the physical address because i want to store the PPN at that PTE that will be added with the offset to get the physical address of page.
Let me know if you have any doubt?
la t2, inner_page_table gives us the base addr of level0 page table that will be added with VPN[0] to get the PTE address from where we will be getting the PPNs for physical frame.

**Comment by FahkingName** [comment]
> I have shifted the physical address because i want to store the PPN at that PTE that will be added with the offset to get the physical address of page. Let me know if you have any doubt? la t2, inner_page_table gives us the base addr of level0 page table that will be added with VPN[0] to get the PTE address from where we will be getting the PPNs for physical frame.

Thanks for your help. It turns out that I still have to carefully read the RISC-V manual.
